export const browserCoreExamples = [
  "clawbot browser status",
  "clawbot browser start",
  "clawbot browser stop",
  "clawbot browser tabs",
  "clawbot browser open https://example.com",
  "clawbot browser focus abcd1234",
  "clawbot browser close abcd1234",
  "clawbot browser screenshot",
  "clawbot browser screenshot --full-page",
  "clawbot browser screenshot --ref 12",
  "clawbot browser snapshot",
  "clawbot browser snapshot --format aria --limit 200",
  "clawbot browser snapshot --efficient",
  "clawbot browser snapshot --labels",
];

export const browserActionExamples = [
  "clawbot browser navigate https://example.com",
  "clawbot browser resize 1280 720",
  "clawbot browser click 12 --double",
  'clawbot browser type 23 "hello" --submit',
  "clawbot browser press Enter",
  "clawbot browser hover 44",
  "clawbot browser drag 10 11",
  "clawbot browser select 9 OptionA OptionB",
  "clawbot browser upload /tmp/file.pdf",
  'clawbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "clawbot browser dialog --accept",
  'clawbot browser wait --text "Done"',
  "clawbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "clawbot browser console --level error",
  "clawbot browser pdf",
];
